### ISSUE TITLE
Docker smoke test ModuleNotFoundError No module named 'absl'

### ISSUE THREAD

**Issue by abettati** [google-research/circuit_training#51]
While trying out the docker Image I get this error
```
~/work/circuit-training$ docker run -it --rm -v $(pwd):/workspace --workdir /workspace circuit_training:core bash
root@7fd85732683b:/workspace/circuit-training# python3 -m circuit_training.environment.environment_test
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/circuit-training/circuit_training/environment/environment_test.py", line 19, in <module>
    from absl import flags
ModuleNotFoundError: No module named 'absl'
```

I think the build command went through (here cached):
```
~/work/circuit-training$ docker build --tag circuit_training:core -f tools/docker/ubuntu_circuit_training tools/docker/
[+] Building 1.5s (20/20) FINISHED                                                                                                                                                                          
 => [internal] load build definition from ubuntu_circuit_training                                                                                                                                      0.0s
 => => transferring dockerfile: 3.85kB                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                        1.4s
 => [ 1/16] FROM docker.io/library/ubuntu:20.04@sha256:24a0df437301598d1a4b62ddf59fa0ed2969150d70d748c84225e6501e9c36b9                                                                                0.0s
 => CACHED [ 2/16] RUN apt-get -o Acquire::Retries=3 -y update && apt-get -o Acquire::Retries=3 -y install -y --no-install-recommends         software-properties-common         curl         tmux     0.0s
 => CACHED [ 3/16] RUN add-apt-repository ppa:deadsnakes/ppa                                                                                                                                           0.0s
 => CACHED [ 4/16] RUN apt-get -o Acquire::Retries=3 -y update && apt-get -o Acquire::Retries=3 -y install -y --no-install-recommends         python3.9-dev         python3.9-distutils         &&     0.0s
 => CACHED [ 5/16] RUN curl https://storage.googleapis.com/rl-infra-public/circuit-training/placement_cost/plc_wrapper_main      -o  /usr/local/bin/plc_wrapper_main                                   0.0s
 => CACHED [ 6/16] RUN chmod 555 /usr/local/bin/plc_wrapper_main                                                                                                                                       0.0s
 => CACHED [ 7/16] RUN curl -O https://bootstrap.pypa.io/get-pip.py                                                                                                                                    0.0s
 => CACHED [ 8/16] RUN python3.9 get-pip.py                                                                                                                                                            0.0s
 => CACHED [ 9/16] RUN python3.9 -mpip --no-cache-dir install tf-agents[reverb] sortedcontainers tox pytest                                                                                            0.0s
 => CACHED [10/16] RUN apt-get update         && apt-get install -y             wget             flex             libcairo2-dev             libboost-all-dev                                           0.0s
 => CACHED [11/16] RUN python3.9 -mpip install pyunpack>=0.1.2         patool>=1.12         timeout-decorator>=0.5.0         matplotlib>=2.2.2         cairocffi>=0.9.0         pkgconfig>=1.4.0       0.0s
 => CACHED [12/16] RUN python3.9 -mpip install numpy==1.23.5 # Required by tensorflow until fixed ~TF 2.12+                                                                                            0.0s
 => CACHED [13/16] RUN mkdir -p /dreamplace                                                                                                                                                            0.0s
 => CACHED [14/16] RUN curl https://storage.googleapis.com/rl-infra-public/circuit-training/dreamplace/dreamplace_python3.9.tar.gz -o /dreamplace/dreamplace.tar.gz                                    0.0s
 => CACHED [15/16] RUN tar xzf /dreamplace/dreamplace.tar.gz -C /dreamplace/                                                                                                                           0.0s
 => CACHED [16/16] RUN python3.9 -m pip freeze                                                                                                                                                         0.0s
 => exporting to image                                                                                                                                                                                 0.0s
 => => exporting layers                                                                                                                                                                                0.0s
 => => writing image sha256:650e0e691d2ae5db40e76416db4f47b6317b16ecb7b6c2093aa44757bc814b5c                                                                                                           0.0s
 => => naming to docker.io/library/circuit_training:core
```

Did I miss something or is the 'absl' package actually missing from the docker image?

**Comment by abettati** [comment]
You are right, defualt python in my container is 3.8
```
root@882a26d2ae64:/workspace# python3
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

If I run with `python3.9 -m circuit_training.environment.environment_test` it goes further.
It still fails 1 test though:
```
root@882a26d2ae64:/workspace# python3.9 -m circuit_training.environment.environment_test
2023-04-12 02:40:09.994638: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-04-12 02:40:10.246438: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-04-12 02:40:11.468534: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-04-12 02:40:11.475281: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-12 02:40:14.729153: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (5.1.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Running tests under Python 3.9.16: /usr/bin/python3.9
[ RUN      ] EnvironmentTest.test_action_space
I0412 02:40:28.219354 139657645123392 environment.py:216] ***Num node to place***:2
I0412 02:40:28.223868 139657645123392 placement_util.py:447] node_order: descending_size_macro_first
I0412 02:40:28.245094 139657645123392 observation_extractor.py:320] Pad a tensor with shape (5,) by 42000
I0412 02:40:28.255223 139657645123392 observation_extractor.py:334] Pad a tensor with shape (5,) by 3500
INFO:tensorflow:time(__main__.EnvironmentTest.test_action_space): 0.34s
I0412 02:40:28.288695 139657645123392 test_util.py:2467] time(__main__.EnvironmentTest.test_action_space): 0.34s
[       OK ] EnvironmentTest.test_action_space
[ RUN      ] EnvironmentTest.test_create_and_obs_space
I0412 02:40:28.368595 139657645123392 environment.py:216] ***Num node to place***:2
I0412 02:40:28.370536 139657645123392 placement_util.py:447] node_order: descending_size_macro_first
I0412 02:40:28.376635 139657645123392 observation_extractor.py:320] Pad a tensor with shape (5,) by 42000
I0412 02:40:28.377619 139657645123392 observation_extractor.py:334] Pad a tensor with shape (5,) by 3500
INFO:tensorflow:time(__main__.EnvironmentTest.test_create_and_obs_space): 0.11s
I0412 02:40:28.401192 139657645123392 test_util.py:2467] time(__main__.EnvironmentTest.test_create_and_obs_space): 0.11s
[       OK ] EnvironmentTest.test_create_and_obs_space
[ RUN      ] EnvironmentTest.test_infisible
I0412 02:40:28.482485 139657645123392 environment.py:216] ***Num node to place***:2
I0412 02:40:28.485958 139657645123392 placement_util.py:447] node_order: descending_size_macro_first
I0412 02:40:28.503776 139657645123392 observation_extractor.py:320] Pad a tensor with shape (5,) by 42000
I0412 02:40:28.505141 139657645123392 observation_extractor.py:334] Pad a tensor with shape (5,) by 3500
INFO:tensorflow:time(__main__.EnvironmentTest.test_infisible): 0.12s
I0412 02:40:28.524590 139657645123392 test_util.py:2467] time(__main__.EnvironmentTest.test_infisible): 0.12s
[       OK ] EnvironmentTest.test_infisible
[ RUN      ] EnvironmentTest.test_save_file_train_step
I0412 02:40:28.815208 139657645123392 environment.py:216] ***Num node to place***:2
I0412 02:40:28.817175 139657645123392 placement_util.py:447] node_order: descending_size_macro_first
I0412 02:40:28.824875 139657645123392 observation_extractor.py:320] Pad a tensor with shape (5,) by 42000
I0412 02:40:28.828542 139657645123392 observation_extractor.py:334] Pad a tensor with shape (5,) by 3500
I0412 02:40:28.889569 139657645123392 placement_util.py:447] node_order: random
I0412 02:40:28.895797 139657645123392 dreamplace_util.py:104] Update num_bins_x and num_bins_y: (128, 128)
I0412 02:40:28.902512 139657645123392 plc_converter.py:141] Node 8 is placed at (170.000000, 230.000000).
I0412 02:40:28.907457 139657645123392 plc_converter.py:141] Node 2 is placed at (375.000000, 375.000000).
I0412 02:40:28.909322 139657645123392 plc_converter.py:141] Node 3 is placed at (125.000000, 125.000000).
I0412 02:40:28.911084 139657645123392 plc_converter.py:141] Node 0 is placed at (0.000000, 100.000000).
I0412 02:40:28.912482 139657645123392 plc_converter.py:141] Node 1 is placed at (499.000000, 499.000000).
INFO:tensorflow:time(__main__.EnvironmentTest.test_save_file_train_step): 0.4s
I0412 02:40:28.929174 139657645123392 test_util.py:2467] time(__main__.EnvironmentTest.test_save_file_train_step): 0.4s
[  FAILED  ] EnvironmentTest.test_save_file_train_step
[ RUN      ] EnvironmentTest.test_session
[  SKIPPED ] EnvironmentTest.test_session
[ RUN      ] EnvironmentTest.test_validate_circuite_env
I0412 02:40:29.045726 139657645123392 environment.py:216] ***Num node to place***:2
I0412 02:40:29.048648 139657645123392 placement_util.py:447] node_order: descending_size_macro_first
I0412 02:40:29.060537 139657645123392 observation_extractor.py:320] Pad a tensor with shape (5,) by 42000
I0412 02:40:29.064798 139657645123392 observation_extractor.py:334] Pad a tensor with shape (5,) by 3500
INFO:tensorflow:time(__main__.EnvironmentTest.test_validate_circuite_env): 0.25s
I0412 02:40:29.188475 139657645123392 test_util.py:2467] time(__main__.EnvironmentTest.test_validate_circuite_env): 0.25s
[       OK ] EnvironmentTest.test_validate_circuite_env
[ RUN      ] EnvironmentTest.test_wrap_tfpy_environment
I0412 02:40:29.263710 139657645123392 environment.py:216] ***Num node to place***:2
I0412 02:40:29.265571 139657645123392 placement_util.py:447] node_order: descending_size_macro_first
I0412 02:40:29.270780 139657645123392 observation_extractor.py:320] Pad a tensor with shape (5,) by 42000
I0412 02:40:29.271743 139657645123392 observation_extractor.py:334] Pad a tensor with shape (5,) by 3500
/usr/lib/python3.9/multiprocessing/pool.py:265: ResourceWarning: unclosed running multiprocessing pool <multiprocessing.pool.ThreadPool state=RUN pool_size=1>
  _warn(f"unclosed running multiprocessing pool {self!r}",
ResourceWarning: Enable tracemalloc to get the object allocation traceback
INFO:tensorflow:time(__main__.EnvironmentTest.test_wrap_tfpy_environment): 0.13s
I0412 02:40:29.319782 139657645123392 test_util.py:2467] time(__main__.EnvironmentTest.test_wrap_tfpy_environment): 0.13s
[       OK ] EnvironmentTest.test_wrap_tfpy_environment
======================================================================
ERROR: test_save_file_train_step (__main__.EnvironmentTest)
EnvironmentTest.test_save_file_train_step
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/circuit_training/environment/environment_test.py", line 149, in test_save_file_train_step
    obs, _, done, _ = env.step(action)
  File "/workspace/circuit_training/environment/environment.py", line 575, in step
    cost, info = self.call_analytical_placer_and_get_cost()
  File "/workspace/circuit_training/environment/environment.py", line 459, in call_analytical_placer_and_get_cost
    self._save_placement(cost)
  File "/workspace/circuit_training/environment/environment.py", line 427, in _save_placement
    self._run_cd()
  File "/workspace/circuit_training/environment/environment.py", line 389, in _run_cd
    cd = cd_placer.CoordinateDescentPlacer(plc=self._plc, cost_fn=cost_fn)
  File "/usr/local/lib/python3.9/dist-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.9/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.9/dist-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/workspace/circuit_training/environment/coordinate_descent_placer.py", line 149, in __init__
    self._dreamplace = dreamplace_core.SoftMacroPlacer(
  File "/usr/local/lib/python3.9/dist-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.9/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.9/dist-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/workspace/circuit_training/dreamplace/dreamplace_core.py", line 34, in __init__
    self.placedb_plc = placedb_plc.PlacedbPlc(plc, params, hard_macro_order)
  File "/workspace/circuit_training/dreamplace/placedb_plc.py", line 31, in __init__
    self.placedb = self.converter.convert(plc, hard_macro_order)
  File "/workspace/circuit_training/dreamplace/plc_converter.py", line 524, in convert
    convert_to_ndarray(db)
  File "/workspace/circuit_training/dreamplace/plc_converter.py", line 404, in convert_to_ndarray
    db.flat_node2pin_map, db.flat_node2pin_start_map = db.flatten_nested_map(
AttributeError: 'PlaceDB' object has no attribute 'flatten_nested_map'
  In call to configurable 'SoftMacroPlacer' (<class 'circuit_training.dreamplace.dreamplace_core.SoftMacroPlacer'>)
  In call to configurable 'CoordinateDescentPlacer' (<class 'circuit_training.environment.coordinate_descent_placer.CoordinateDescentPlacer'>)
```
Looks like it is calling a wrong version of DREAMPlace?
