### ISSUE TITLE
Errors using grouper_main.py script

### ISSUE THREAD

**Issue by RaidToRadar** [google-research/circuit_training#56]
Hello, I just translated my lef/def files and generated a .pb.txt file but I am having issues setting up and running the pre-processing state before I can use CT. The grouper_main.py has multiple issues in terms of importing modules and also with adding a BLOCK_NAME (says to add it inside the pb.txt file but is not stated in the READ.ME tutorial). If at all possible, what kind of environment and dependencies should I install to get this to work or is it ran in the docker here are some example errors that I would get.

```bash
(my_venv) vboxuser@HELPME:~/circuit_training$ python3.9 circuit_training/grouping/grouper_main.py --output_dir=$OUTPUT_DIR --netlist_file=$NETLIST_FILE --block_name=$BLOCK_NAME --hmetis_dir=$HMETIS_DIR
Traceback (most recent call last):
  File "/home/vboxuser/circuit_training/circuit_training/grouping/grouper_main.py", line 36, in <module>
    from circuit_training.grouping import grouper
ModuleNotFoundError: No module named 'circuit_training'
```
whenever I run this inside the docker I no longer get the error but instead get another error stating about adding the block_name inside the pb.txt file :

```bash
root@b0b80216d06c:/workspace# python3.9 circuit_training/grouping/grouper_main.py --out
put_dir=$OUTPUT_DIR --netlist_file=$NETLIST_FILE --block_name=$BLOCK_NAME --hmetis_dir=
$HMETIS_DIR --plc_wrapper_main=$PLC_WRAPPER_MAIN
2023-06-16 16:04:44.672398: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-16 16:04:44.749733: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-16 16:04:44.750115: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-16 16:04:45.543137: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (5.1.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
W0616 16:04:46.501832 140120903472960 placement_util.py:231] block_name is not set. Please add the block_name in:
/workspace/eda-ml/Test2/defs/nangate45_gcd_io.pb.txt
or in:
None
Traceback (most recent call last):
  File "/workspace/circuit_training/grouping/grouper_main.py", line 62, in <module>
    app.run(main)
  File "/usr/local/lib/python3.9/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.9/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/workspace/circuit_training/grouping/grouper_main.py", line 53, in main
    grouped_plc, placement_file = grouper.group_stdcells(
  File "/workspace/circuit_training/grouping/grouper.py", line 429, in group_stdcells
    plc = create_placement_cost_fn(netlist_file=netlist_file)
  File "/workspace/circuit_training/environment/placement_util.py", line 236, in create_placement_cost
    plc = plc_client.PlacementCost(netlist_file, macro_macro_x_spacing,
  File "/workspace/circuit_training/environment/plc_client.py", line 68, in __init__
    self.process = subprocess.Popen([str(a) for a in args])
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/workspace/eda-ml/plc_wrapper_main'
Exception ignored in: <function PlacementCost.__del__ at 0x7f707048b940>
Traceback (most recent call last):
  File "/workspace/circuit_training/environment/plc_client.py", line 114, in __del__
AttributeError: 'function' object has no attribute 'close'
root@b0b80216d06c:/workspace#
```

Can someone please point me in the right direction.

**Comment by esonghori** [comment]
The missing block name is a warning. The problem is `plc_wrapper_main`. Looks like it is either missing or you don't have read and execution permission.
