### ISSUE TITLE
Error while training PPO agent

### ISSUE THREAD

**Issue by samhithasanka** [google-research/circuit_training#58]
python3 -m circuit_training.learning.train_ppo        --root_dir=${ROOT_DIR}        --std_cell_placer_mode=FD        --replay_buffer_server_address=${REVERB_SERVER}        --variable_container_server_address=${REVERB_SERVER}        --sequence_length=134        --gin_bindings='train.num_iterations=200'       --netlist_file=${NETLIST_FILE}        --init_placement=${INIT_PLACEMENT}        --global_seed=${GLOBAL_SEED}

**_I'm running train_ppo using the above command_**
_I am getting this error. I have launched reverb server. I am not using any docker_.

2023-06-19 14:13:39.798528: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-19 14:13:39.830979: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:7697] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-06-19 14:13:39.831030: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-06-19 14:13:39.831050: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-06-19 14:13:39.837003: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-19 14:13:39.837239: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-19 14:13:40.386722: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
I0619 14:13:42.663258 140531667562496 train_ppo.py:92] global seed=111
I0619 14:13:44.359349 140531667562496 environment.py:216] ***Num node to place***:133
I0619 14:13:44.449179 140531667562496 placement_util.py:447] node_order: descending_size_macro_first
W0619 14:13:44.953677 140531667562496 plc_client.py:96] JSONDecode Error for GetMacroAndClusteredPortAdjacency
 Expecting value: line 1 column 219265 (char 219264)
I0619 14:13:44.953792 140531667562496 plc_client.py:98] Looking for more data for GetMacroAndClusteredPortAdjacency on connection:0/256
W0619 14:13:44.963603 140531667562496 plc_client.py:96] JSONDecode Error for GetMacroAndClusteredPortAdjacency
 Expecting ',' delimiter: line 1 column 438529 (char 438528)
I0619 14:13:44.963649 140531667562496 plc_client.py:98] Looking for more data for GetMacroAndClusteredPortAdjacency on connection:1/256
W0619 14:13:44.979751 140531667562496 plc_client.py:96] JSONDecode Error for GetMacroAndClusteredPortAdjacency
 Expecting value: line 1 column 657793 (char 657792)
I0619 14:13:44.979862 140531667562496 plc_client.py:98] Looking for more data for GetMacroAndClusteredPortAdjacency on connection:2/256
W0619 14:13:45.003510 140531667562496 plc_client.py:96] JSONDecode Error for GetMacroAndClusteredPortAdjacency
 Expecting ',' delimiter: line 1 column 877057 (char 877056)
I0619 14:13:45.003634 140531667562496 plc_client.py:98] Looking for more data for GetMacroAndClusteredPortAdjacency on connection:3/256
W0619 14:13:45.031592 140531667562496 plc_client.py:96] JSONDecode Error for GetMacroAndClusteredPortAdjacency
 Expecting value: line 1 column 1096321 (char 1096320)
I0619 14:13:45.031708 140531667562496 plc_client.py:98] Looking for more data for GetMacroAndClusteredPortAdjacency on connection:4/256
W0619 14:13:45.062884 140531667562496 plc_client.py:96] JSONDecode Error for GetMacroAndClusteredPortAdjacency
 Expecting value: line 1 column 1315585 (char 1315584)
I0619 14:13:45.063026 140531667562496 plc_client.py:98] Looking for more data for GetMacroAndClusteredPortAdjacency on connection:5/256
W0619 14:13:45.100739 140531667562496 plc_client.py:96] JSONDecode Error for GetMacroAndClusteredPortAdjacency
 Expecting value: line 1 column 1534849 (char 1534848)
I0619 14:13:45.100874 140531667562496 plc_client.py:98] Looking for more data for GetMacroAndClusteredPortAdjacency on connection:6/256
W0619 14:13:45.140887 140531667562496 plc_client.py:96] JSONDecode Error for GetMacroAndClusteredPortAdjacency
 Expecting value: line 1 column 1754113 (char 1754112)
I0619 14:13:45.141026 140531667562496 plc_client.py:98] Looking for more data for GetMacroAndClusteredPortAdjacency on connection:7/256
I0619 14:13:45.491459 140531667562496 observation_extractor.py:320] Pad a tensor with shape (8312,) by 42000
I0619 14:13:45.491828 140531667562496 observation_extractor.py:334] Pad a tensor with shape (953,) by 3500
I0619 14:13:45.568008 140531667562496 train_ppo_lib.py:214] Initialize iteration at: init_iteration 0.
I0619 14:13:45.569200 140531667562496 train_ppo_lib.py:229] Initialize train_step at 0
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/a0393510local/circuit_training/circuit_training/learning/train_ppo.py", line 154, in <module>
    multiprocessing.handle_main(functools.partial(app.run, main))
  File "/home/a0393510local/.local/lib/python3.10/site-packages/tf_agents/system/default/multiprocessing_core.py", line 77, in handle_main
    return app.run(parent_main_fn, *args, **kwargs)
  File "/home/a0393510local/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/a0393510local/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/a0393510local/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/a0393510local/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/a0393510local/circuit_training/circuit_training/learning/train_ppo.py", line 134, in main
    train_ppo_lib.train(
  File "/home/a0393510local/.local/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/a0393510local/.local/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/a0393510local/.local/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/a0393510local/circuit_training/circuit_training/learning/train_ppo_lib.py", line 272, in train
    variable_container = reverb_variable_container.ReverbVariableContainer(
  File "/home/a0393510local/.local/lib/python3.10/site-packages/tf_agents/experimental/distributed/reverb_variable_container.py", line 70, in __init__
    server_info = reverb.Client(server_address).server_info()
  File "/home/a0393510local/.local/lib/python3.10/site-packages/reverb/client.py", line 500, in server_info
    info_proto_strings = self._client.ServerInfo(timeout or 0)
RuntimeError: Socket closed
  In call to configurable 'train' (<function train at 0x7fcf2c355480>)
_**Could anyone suggest me how to resolve it**_

**Comment by JIEEEN** [comment]
same issue
