### ISSUE TITLE
[e2e_smoke test] SoftMacroPlacer place() timed out

### ISSUE THREAD

**Issue by samli50801** [google-research/circuit_training#70]
After entering the command
$ bash tools/e2e_smoke_test.sh --root_dir logs/run_00

My training job and collect job shows the timeout error:
```
TimeoutError: 'SoftMacroPlacer place() timed out.'
```

Training job:
```
I1029 00:23:57.387345 140129102296896 NonLinearPlace.py:311] optimizer step 834.291 ms
I1029 00:23:57.387835 140129102296896 NonLinearPlace.py:318] iteration  225, ( 225,  0,  0), Obj 3.027075E+04, DensityWeight 1.739096E-04, HPWL 3.054394E+05, Overflow 8.294092E-01, MaxDensity 5.174E+01, gamma 9.411782E+01, time 129.017ms
I1029 00:23:57.388154 140129102296896 NonLinearPlace.py:327] full step 979.749 ms
I1029 00:23:58.373557 140129102296896 NonLinearPlace.py:311] optimizer step 832.958 ms
I1029 00:23:58.373730 140129102296896 NonLinearPlace.py:318] iteration  226, ( 226,  0,  0), Obj 3.150701E+04, DensityWeight 1.825153E-04, HPWL 3.085738E+05, Overflow 8.252056E-01, MaxDensity 5.394E+01, gamma 9.310868E+01, time 126.417ms
I1029 00:23:58.373864 140129102296896 NonLinearPlace.py:327] full step 985.209 ms
I1029 00:23:59.420236 140129102296896 NonLinearPlace.py:311] optimizer step 867.430 ms
I1029 00:23:59.420845 140129102296896 NonLinearPlace.py:318] iteration  227, ( 227,  0,  0), Obj 3.250768E+04, DensityWeight 1.915574E-04, HPWL 3.121429E+05, Overflow 8.226960E-01, MaxDensity 5.324E+01, gamma 9.112736E+01, time 132.052ms
I1029 00:23:59.427514 140129102296896 NonLinearPlace.py:327] full step 1053.256 ms
I1029 00:24:00.423436 140129102296896 NonLinearPlace.py:311] optimizer step 868.528 ms
I1029 00:24:00.424076 140129102296896 NonLinearPlace.py:318] iteration  228, ( 228,  0,  0), Obj 3.387368E+04, DensityWeight 2.010352E-04, HPWL 3.154094E+05, Overflow 8.202477E-01, MaxDensity 5.327E+01, gamma 8.996461E+01, time 110.273ms
I1029 00:24:00.424436 140129102296896 NonLinearPlace.py:327] full step 996.379 ms
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/learning/train_ppo.py", line 370, in <module>
    multiprocessing.handle_main(functools.partial(app.run, main))
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/tf_agents/system/default/multiprocessing_core.py", line 76, in handle_main
    return app.run(parent_main_fn, *args, **kwargs)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/learning/train_ppo.py", line 321, in main
    env = create_env_fn()
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/environment/environment.py", line 627, in create_circuit_environment
    env = CircuitEnv(*args, **kwarg)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/environment/environment.py", line 258, in __init__
    converged = self._dreamplace.place()
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/dreamplace/dreamplace_core.py", line 65, in place
    return decorated_place()
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/dreamplace/dreamplace_core.py", line 62, in decorated_place
    return self._place()
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/dreamplace/dreamplace_core.py", line 49, in _place
    metrics = nonlinear_place(self.params, self.placedb_plc.placedb)
  File "/ads/yuclee3u/google2/circuit_training/dreamplace/dreamplace/NonLinearPlace.py", line 448, in __call__
    one_descent_step(
  File "/ads/yuclee3u/google2/circuit_training/dreamplace/dreamplace/NonLinearPlace.py", line 280, in one_descent_step
    cur_metric.evaluate(placedb, eval_ops, pos, model.data_collections)
  File "/ads/yuclee3u/google2/circuit_training/dreamplace/dreamplace/EvalMetrics.py", line 111, in evaluate
    self.hpwl = ops["hpwl"](var).data
  File "/ads/yuclee3u/google2/circuit_training/dreamplace/dreamplace/BasicPlace.py", line 508, in build_wirelength_op
    return wirelength_for_pin_op(pin_pos_op(pos))
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ads/yuclee3u/google2/circuit_training/dreamplace/dreamplace/ops/pin_pos/pin_pos.py", line 152, in forward
    return PinPosFunction.apply(pos, self.pin_offset_x,
  File "/ads/yuclee3u/google2/circuit_training/dreamplace/dreamplace/ops/pin_pos/pin_pos.py", line 35, in forward
    output = func(ctx.pos, pin_offset_x, pin_offset_y, pin2node_map,
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/timeout_decorator/timeout_decorator.py", line 69, in handler
    _raise_exception(timeout_exception, exception_message)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/timeout_decorator/timeout_decorator.py", line 47, in _raise_exception
    raise exception(exception_message)
timeout_decorator.timeout_decorator.TimeoutError: 'SoftMacroPlacer place() timed out.'
  In call to configurable 'CircuitEnv' (<class 'circuit_training.environment.environment.CircuitEnv'>)
Collect job failed (SIGUSR1). Check logs/run_00/collect_*.log.
Exiting with code 8.
```

Collect job:
```
I1029 00:23:59.115634 139831298479936 NonLinearPlace.py:318] iteration  226, ( 226,  0,  0), Obj 3.135840E+04, DensityWeight 1.806198E-04, HPWL 3.079181E+05, Overflow 8.261681E-01, MaxDensity 5.359E+01, gamma 9.320588E+01, time 108.695ms
I1029 00:23:59.115787 139831298479936 NonLinearPlace.py:327] full step 992.862 ms
I1029 00:24:00.087282 139831298479936 NonLinearPlace.py:311] optimizer step 828.702 ms
I1029 00:24:00.087450 139831298479936 NonLinearPlace.py:318] iteration  227, ( 227,  0,  0), Obj 3.235684E+04, DensityWeight 1.895669E-04, HPWL 3.115174E+05, Overflow 8.237305E-01, MaxDensity 5.323E+01, gamma 9.157729E+01, time 114.419ms
I1029 00:24:00.087578 139831298479936 NonLinearPlace.py:327] full step 971.391 ms
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/learning/ppo_collect.py", line 114, in <module>
    multiprocessing.handle_main(functools.partial(app.run, main))
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/tf_agents/system/default/multiprocessing_core.py", line 76, in handle_main
    return app.run(parent_main_fn, *args, **kwargs)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/learning/ppo_collect.py", line 95, in main
    ppo_collect_lib.collect(
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/learning/ppo_collect_lib.py", line 61, in collect
    env = create_env_fn(train_step=train_step)
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/environment/environment.py", line 627, in create_circuit_environment
    env = CircuitEnv(*args, **kwarg)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/environment/environment.py", line 258, in __init__
    converged = self._dreamplace.place()
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/dreamplace/dreamplace_core.py", line 65, in place
    return decorated_place()
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/dreamplace/dreamplace_core.py", line 62, in decorated_place
    return self._place()
  File "/ads/yuclee3u/google2/circuit_training/circuit_training/dreamplace/dreamplace_core.py", line 49, in _place
    metrics = nonlinear_place(self.params, self.placedb_plc.placedb)
  File "/ads/yuclee3u/google2/circuit_training/dreamplace/dreamplace/NonLinearPlace.py", line 448, in __call__
    one_descent_step(
  File "/ads/yuclee3u/google2/circuit_training/dreamplace/dreamplace/NonLinearPlace.py", line 309, in one_descent_step
    optimizer.step()
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/ads/yuclee3u/google2/circuit_training/dreamplace/dreamplace/NesterovAcceleratedGradientOptimizer.py", line 121, in step
    f_kp1, g_kp1 = obj_and_grad_fn(v_kp1)
  File "/ads/yuclee3u/google2/circuit_training/dreamplace/dreamplace/PlaceObj.py", line 389, in obj_and_grad_fn
    obj.backward()
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/torch/autograd/function.py", line 267, in apply
    return user_fn(self, *args)
  File "/ads/yuclee3u/google2/circuit_training/dreamplace/dreamplace/ops/weighted_average_wirelength/weighted_average_wirelength.py", line 207, in backward
    output[:int(output.numel() // 2)].masked_fill_(ctx.pin_mask, 0.0)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/timeout_decorator/timeout_decorator.py", line 69, in handler
    _raise_exception(timeout_exception, exception_message)
  File "/ads/yuclee3u/google2/lib64/python3.9/site-packages/timeout_decorator/timeout_decorator.py", line 47, in _raise_exception
    raise exception(exception_message)
timeout_decorator.timeout_decorator.TimeoutError: 'SoftMacroPlacer place() timed out.'
  In call to configurable 'CircuitEnv' (<class 'circuit_training.environment.environment.CircuitEnv'>)
  In call to configurable 'collect' (<function collect at 0x7f2cec06fc10>)
```
Reverb job:
```
I1029 00:52:07.471794 140393257813824 train_utils.py:236] Waiting for `wait_predicate_fn`. Block execution. Sleeping for 2 seconds.
I1029 00:52:09.473108 140393257813824 train_utils.py:236] Waiting for `wait_predicate_fn`. Block execution. Sleeping for 2 seconds.
I1029 00:52:11.475460 140393257813824 train_utils.py:236] Waiting for `wait_predicate_fn`. Block execution. Sleeping for 2 seconds.
I1029 00:52:13.477776 140393257813824 train_utils.py:236] Waiting for `wait_predicate_fn`. Block execution. Sleeping for 2 seconds.
I1029 00:52:15.480091 140393257813824 train_utils.py:236] Waiting for `wait_predicate_fn`. Block execution. Sleeping for 2 seconds.
I1029 00:52:17.482401 140393257813824 train_utils.py:236] Waiting for `wait_predicate_fn`. Block execution. Sleeping for 2 seconds.
I1029 00:52:19.484104 140393257813824 train_utils.py:236] Waiting for `wait_predicate_fn`. Block execution. Sleeping for 2 seconds.
I1029 00:52:21.486089 140393257813824 train_utils.py:236] Waiting for `wait_predicate_fn`. Block execution. Sleeping for 2 seconds.
```

I'm not sure what causes the 'SoftMacroPlacer place() timed out.' issue

**Comment by Li-auto-s** [comment]
Could you help to explain how to resolve this ？ I also met this issue .
